apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.16.5
appVersion: 2.0.5
dependencies:
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 23.2.2
  condition: components.redis
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.38.0
- name: mariadb
  version: 25.0.10
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
