apiVersion: v2
name: bumblebee
description: A Helm chart for Kubernetes
type: application
version: 0.1.3
appVersion: a99568a
dependencies:
- name: redis
  version: 15.5.4
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
