apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 0.2.18
appVersion: 69edc28
dependencies:
- name: redis
  version: 15.5.4
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
