apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.12.19
appVersion: 2d230d5
dependencies:
- name: redis
  version: 20.2.1
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x
