apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.0.37
appVersion: 52cbf83
dependencies:
- name: redis
  version: 16.13.2
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
