apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.12.40
appVersion: 36a7d85
dependencies:
- name: redis
  version: 20.11.4
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x
