apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.12.37
appVersion: db1b57a
dependencies:
- name: redis
  version: 20.10.0
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x
