apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.16.9
appVersion: 2.0.9
dependencies:
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 27.0.10
  condition: components.redis
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.38.0
- name: mariadb
  version: 26.1.5
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: components.mariadb
