apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 0.1.33
appVersion: 1ff1976
dependencies:
- name: redis
  version: 15.5.4
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
