apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.12.30
appVersion: 8779a9d
dependencies:
- name: redis
  version: 20.3.0
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x
