apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 0.2.76
appVersion: 5100d32
dependencies:
- name: redis
  version: 15.7.6
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
