apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.14.0
appVersion: a73e1ed
dependencies:
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 22.0.1
  condition: components.redis
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.3

