apiVersion: v2
name: bumblebee
description: A Helm chart for Kubernetes
type: application
version: 0.1.2
appVersion: $IMAGE_TAG
dependencies:
- name: redis
  version: 15.5.4
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
