apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.12.42
appVersion: a73e1ed
dependencies:
- name: redis
  version: 21.1.8
  repository: https://charts.bitnami.com/bitnami
  condition: components.redis
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x
