apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.15.4
appVersion: b45184b
dependencies:
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 23.2.1
  condition: components.redis
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.4
