apiVersion: v2
name: bumblebee
description: A Helm chart for Bumblebee
type: application
version: 1.15.1
appVersion: de3a09e
dependencies:
- name: redis
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 22.0.7
  condition: components.redis
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 2.31.4
