# Default values for bumblebee.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


bumblebee:
  image:
    repository: registry.rc.nectar.org.au/nectar/bumblebee
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
  pdb:
    enabled: false
    minAvailable: 0
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  replicaCount: 1
  resources: {}

rqworker:
  pdb:
    enabled: false
    minAvailable: 0
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  replicaCount: 1
  resources: {}

rqscheduler:
  pdb:
    enabled: false
    minAvailable: 0
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  nodeAffinityPreset:
    type: ""
    key: ""
    values: []
  affinity: {}
  replicaCount: 1
  resources: {}

conf:
  DEBUG: False
  ALLOWED_HOSTS: '*'
  SITE_URL: ''
  GUACAMOLE_URL_TEMPLATE: ''
  OS_APPLICATION_CREDENTIAL_ID: ''
  OS_AUTH_URL: https://keystone.rc.nectar.org.au:5000/v3
  OS_PROJECT_ID: ''
  OS_NETWORK: bumblebee
  OS_SECGROUPS: bumblebee
  OIDC_SERVER_URL: https://sso.rc.nectar.org.au/auth/realms/nectar/protocol/openid-connect
  OIDC_RP_CLIENT_ID: bumblebee
  ENVIRONMENT_NAME: production
  ENVIRONMENT_COLOR: '#ff0000'
  DB_HOST: localhost
  DB_USER: bumblebee
  REDIS_HOST: redis
  EXPIRER_OPTS: '--dry-run --verbose'
  # Overrides for default timeouts (WAIT) and retry counts  in the codebase
  LAUNCH_WAIT: 600
  REBOOT_WAIT: 600
  RESIZE_WAIT: 600
  SHELVE_WAIT: 600
  INSTANCE_LAUNCH_WAIT: 600
  VOLUME_CREATION_WAIT: 600

vault:
  role: k8s
  settings_secret: 'path/to/secret/in/vault'

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

gateway:
  enabled: false
  annotations: {}
  hostnames:
    - chart-example.local
  parentRefs:
    - name: default

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

