apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bumblebee.fullname" . }}-guacamole
  labels:
    {{- include "bumblebee.labels" . | nindent 4 }}
    app.kubernetes.io/component: guacamole
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.guacamole.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bumblebee.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: guacamole
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-secret_envs: "{{ .Values.vault.settings_secret }}"
        vault.hashicorp.com/agent-inject-template-secret_envs: |
          {{ print "{{- with secret \"" .Values.vault.settings_secret "\" -}}" }}
          {{ print "{{- range $key, $val := .Data.data }}" }}
          {{ print "export {{ $key }}=\"{{ $val }}\"" }}
          {{ print "{{- end }}" }}
          {{ print "{{- end -}}" }}
      labels:
        {{- include "bumblebee.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: guacamole
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bumblebee.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: guacamole
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag }}"
          imagePullPolicy: {{ .Values.guacamole.image.pullPolicy }}
          command:
            ['sh', '-c', '. /vault/secrets/secret_envs && /opt/guacamole/bin/start.sh']
          envFrom:
            - configMapRef:
                name: {{ include "bumblebee.fullname" . }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /guacamole
              port: http
          readinessProbe:
            httpGet:
              path: /guacamole
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.guacamole.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.guacamole.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.guacamole.podAffinityPreset "component" "guacamole" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.guacamole.podAntiAffinityPreset "component" "guacamole" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.guacamole.nodeAffinityPreset.type "key" .Values.guacamole.nodeAffinityPreset.key "values" .Values.guacamole.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
