apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bumblebee.fullname" . }}-rqworker
  labels:
    {{- include "bumblebee.labels" . | nindent 4 }}
    app.kubernetes.io/component: rqworker
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.rqworker.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bumblebee.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: rqworker
  template:
    metadata:
      annotations:
        vault.hashicorp.com/role: "{{ .Values.vault.role }}"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-secret_envs: "{{ .Values.vault.settings_secret }}"
        vault.hashicorp.com/agent-inject-template-secret_envs: |
          {{ print "{{- with secret \"" .Values.vault.settings_secret "\" -}}" }}
          {{ print "{{- range $key, $val := .Data.data }}" }}
          {{ print "export {{ $key }}=\"{{ $val }}\"" }}
          {{ print "{{- end }}" }}
          {{ print "{{- end -}}" }}
      labels:
        {{- include "bumblebee.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: rqworker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bumblebee.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.bumblebee.image.repository }}:{{ .Values.bumblebee.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bumblebee.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "bumblebee.fullname" . }}
          command: ['sh', '-c', '. /vault/secrets/secret_envs && /docker-run-rqworker.sh']
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.rqworker.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.rqworker.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.rqworker.podAffinityPreset "component" "rqworker" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.rqworker.podAntiAffinityPreset "component" "rqworker" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.rqworker.nodeAffinityPreset.type "key" .Values.rqworker.nodeAffinityPreset.key "values" .Values.rqworker.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
