apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bumblebee.fullname" . }}
  labels:
    {{- include "bumblebee.labels" . | nindent 4 }}
    app.kubernetes.io/component: bumblebee
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.bumblebee.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bumblebee.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bumblebee
  template:
    metadata:
      annotations:
        {{- include "bumblebee.vaultAnnotations" . | nindent 8 }}
      labels:
        {{- include "bumblebee.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bumblebee
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bumblebee.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.bumblebee.image.repository }}:{{ .Values.bumblebee.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bumblebee.image.pullPolicy }}
          command: ['sh', '-c', '. /vault/secrets/secret_envs && /docker-run-bumblebee.sh']
          envFrom:
            - configMapRef:
                name: {{ include "bumblebee.fullname" . }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: http
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /healthcheck/
              port: http
            initialDelaySeconds: 10
            failureThreshold: 6
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      initContainers:
        - name: {{ .Chart.Name }}-init
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.bumblebee.image.repository }}:{{ .Values.bumblebee.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bumblebee.image.pullPolicy }}
          command: ['sh', '-c', '. /vault/secrets/secret_envs && /docker-setup.sh']
          envFrom:
            - configMapRef:
                name: {{ include "bumblebee.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.bumblebee.affinity }}
      affinity: {{- include "common.tplvalues.render" (dict "value" .Values.bumblebee.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.bumblebee.podAffinityPreset "component" "bumblebee" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.bumblebee.podAntiAffinityPreset "component" "bumblebee" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.bumblebee.nodeAffinityPreset.type "key" .Values.bumblebee.nodeAffinityPreset.key "values" .Values.bumblebee.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
