{{- if .Values.bumblebee.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "bumblebee.fullname" . }}
  labels:
    {{- include "bumblebee.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.bumblebee.pdb.minAvailable | default 0 }}
  selector:
    matchLabels:
      {{- include "bumblebee.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bumblebee
{{- end }}
