apiVersion: v1
kind: Service
metadata:
  name: {{ include "bumblebee.fullname" . }}-guacamole
  labels:
    {{- include "bumblebee.labels" . | nindent 4 }}
spec:
  type: {{ .Values.guacamole.service.type }}
  ports:
    - port: {{ .Values.guacamole.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "bumblebee.name" . }}-guacamole
    app.kubernetes.io/instance: {{ .Release.Name }}
